### ISSUE TITLE
Issue in Xcode 6 iOS 8

### ISSUE THREAD

**Issue by mukyasa** [yeahdongcn/RSTransitionEffect#3]
When we create a view controller for all layout,the animation is not working properly ,The animation starts from, unknown start point ,

**Comment by yeahdongcn** [comment]
Are you using `AutoLayout`?

**Comment by mukyasa** [comment]
ya i figured the same prob ,when we use auto layout then the transition is
not working properly,

what is solution then??

**Comment by yeahdongcn** [comment]
My implementation is only frame manipulation, you have to change all this to constraints.

**Comment by yeahdongcn** [comment]
Or you may change it and send pull request ;)

**Comment by mukyasa** [comment]
hey yeahdongcn,

I have implemented the animation with constraint based,

I have one small issue of jerk at start, can u help me out ,if I share the
code

Thank You

**Comment by yeahdongcn** [comment]
OK, no problem

**Comment by mukyasa** [comment]
Below is the updated constraint zip,

**Comment by mukyasa** [comment]
Hello yeahdongcn,
Have u seen the app,
Did u figured out the prob

**Comment by yeahdongcn** [comment]
Hi Mukyasa, I didn't see your attachment

**Comment by mukyasa** [comment]
hey i have sent again in ur personalized mail(yeahdongcn@gmail.com)
